kind: ConfigMap
apiVersion: v1
metadata:
  name: user-service-config-map
data:
  application.properties: |-
    server.port=8085
    testUser.name=donald-duck
    testUser.age=25
    testUser.pin=400080
    logging.level.org.springframework.web=DEBUG

