kind: ConfigMap
apiVersion: v1
metadata:
  name: user-service-config-map
data:
  application.properties: |-
    server.port=8085
    testUser.age=26
    testUser.pin=400089
    logging.level.org.springframework.web=DEBUG

