apiVersion: v1
kind: Service
metadata:
  name: user-svc
  labels:
    app: user
spec:
  type: NodePort
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app: user
---
apiVersion: v1
kind: Pod
metadata:
  name: user-pod
  labels:
    app: user
spec:
  containers:
  - name: user
    image: user:latest
    ports:
    - containerPort: 8081
